" Win behavior
source $VIMRUNTIME/mswin.vim
behave mswin

" Preferences
set encoding=utf-8
set autochdir
set shiftwidth=4
set tabstop=4
set linebreak
set breakindent
set autoindent
set wrap
set conceallevel=0
set backspace=2
set backspace=indent,eol,start
set fileformat=unix
set fileformats=unix,dos
set nobinary
set relativenumber
syntax on

" Aliases
cnoreabbrev ge browse confirm e
cnoreabbrev ! aliasrun

" Plugins
call plug#begin()
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'airblade/vim-gitgutter'
call plug#end()

" Theming
set t_Co=256
set guifont=Cascadia_Code_PL:h10
colorscheme	Tomorrow-Night
let g:airline_powerline_fonts = 1
let g:airline_theme = 'powerlineish'

" Hide GVim Elements
set guioptions-=m
set guioptions-=T
set guioptions-=r
set guioptions-=L
set guioptions-=e

" Navigation & Shortcuts
" inoremap <C-c> "+y
" inoremap <C-v> <C-o>:"+p<CR>

nnoremap <A-1> 1gt
nnoremap <A-2> 2gt
nnoremap <A-3> 3gt
nnoremap <A-4> 4gt
nnoremap <A-5> 5gt
nnoremap <A-6> 6gt
nnoremap <A-7> 7gt
nnoremap <A-8> 8gt
nnoremap <A-9> 9gt
nnoremap <A-0> 10gt
